url = "https://ozazemjevobvwnklufsf.supabase.co"
anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96YXplbWpldm9idndua2x1ZnNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDM4MTk2MzgsImV4cCI6MjAxOTM5NTYzOH0.puJW7NRnqhxcdlzCVVILi0LbeFNNDVdA9WJhJ_-QG2w"
